#!/bin/bash

try
(
    throwErrors

    echo "Nothing for now"
)
catch || {
    case $ex_code in
        *)
            echox "${text_red}Error:${text_reset} An unexpected exception was thrown"
            throw $ex_code
        ;;
    esac
}
